//! Scans `<workspace>/resources/agents/` and emits a `BUILTIN_HANDLES` slice
//! that `agent::models` `include!()`s.
//!
//! Migrations intentionally freeze their own snapshot of this list rather
//! than using `BUILTIN_HANDLES`, so historical migrations stay reproducible.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let agents_dir = manifest_dir
        .join("..")
        .join("..")
        .join("resources")
        .join("agents");

    println!("cargo:rerun-if-changed={}", agents_dir.display());

    let mut handles: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(&agents_dir) {
        for entry in entries.flatten() {
            if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                continue;
            }
            let Some(name) = entry.file_name().to_str().map(str::to_string) else {
                continue;
            };
            if !is_valid_handle(&name) {
                println!(
                    "cargo:warning=skipping built-in template dir `{name}`: not a valid Handle"
                );
                continue;
            }
            handles.push(name);
        }
    } else {
        panic!(
            "build.rs: could not read built-in agents dir at {}",
            agents_dir.display()
        );
    }
    handles.sort();

    let mut emit = String::from("&[\n");
    for h in &handles {
        emit.push_str(&format!(
            "    crate::core::Handle::const_validated(\"{h}\"),\n"
        ));
    }
    emit.push(']');

    // A named `&str` handle const per built-in, so callers reference a builtin by
    // name (`SYSTEM_AGENT_HANDLE`) without a magic literal. If a template dir is
    // renamed/removed its const vanishes, so any code using it fails to compile -
    // a build-time guarantee the referenced builtin exists.
    let mut consts = String::new();
    for h in &handles {
        let name = h.to_uppercase().replace('-', "_");
        consts.push_str(&format!(
            "/// Handle of the `{h}` built-in agent (`resources/agents/{h}/`).\n\
             pub const {name}_AGENT_HANDLE: &str = \"{h}\";\n"
        ));
    }

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("builtin_handles.rs");
    fs::write(
        &out,
        format!(
            "/// Generated by `build.rs`. Do not edit.\n\
             pub const BUILTIN_HANDLES: &[crate::core::Handle] = {emit};\n\
             {consts}"
        ),
    )
    .expect("write builtin_handles.rs");
}

/// Duplicate of `core::handle::is_valid_handle` (build scripts can't import the crate they build).
fn is_valid_handle(s: &str) -> bool {
    let bytes = s.as_bytes();
    if bytes.len() < 2 || bytes.len() > 32 {
        return false;
    }
    if !bytes[0].is_ascii_lowercase() {
        return false;
    }
    bytes
        .iter()
        .all(|&b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-' || b == b'_')
}
