apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  settings.yml: |
    use_default_settings: true

    server:
      secret_key: "change-me-to-something-random"
      limiter: false

    engines:
      - name: ahmia
        disabled: true
      - name: torch
        disabled: true
      - name: radio browser
        disabled: true

    search:
      formats:
        - html
        - json
